# Generated by Django 4.2.7 on 2023-11-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoCrudOps', '0002_student_age_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
